name: SnifLeaf
options:
  minimumXcodeGenVersion: 2.42.0
  createIntermediateGroups: true
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    majorVersion: 5.10.0
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
  SwiftNIO:
    url: https://github.com/apple/swift-nio.git
    majorVersion: 2.83.0
targets:
  SnifLeaf-iOS:
    platform: iOS 
    type: application
    sources:
      - SnifLeaf/iOS
    configFiles:
      Debug: configs/SnifLeaf-iOS-Debug.xcconfig
      Release: configs/SnifLeaf-iOS-Release.xcconfig
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES
  #macOS application
  SnifLeaf-macOS:
    platform: macOS
    type: application
    sources:
      - SnifLeaf/macOS
    configFiles:
      Debug: configs/SnifLeaf-macOS-Debug.xcconfig
      Release: configs/SnifLeaf-macOS-Release.xcconfig
    dependencies:
      - target: Shared
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES

  # Framework Targets
  Shared:
    platform: macOS
    type: framework
    sources:
      - Shared
    configFiles:
      Debug: configs/Shared-Debug.xcconfig
      Release: configs/Shared-Release.xcconfig
    dependencies:
      - target: SnifLeafCore
  SnifLeafCore:
    platform: macOS
    type: framework
    sources:
      - SnifLeafCore
    configFiles:
      Debug: configs/SnifLeafCore-Debug.xcconfig
      Release: configs/SnifLeafCore-Release.xcconfig
    dependencies:
      - package: Alamofire 
      - package: RealmSwift
  #Test Targets
  SnifLeaf-macOSTests:
    platform: macOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/SnifLeaf-macOSTests.xcconfig
    sources:
      - Tests/SnifLeaf-macOSTests
    dependencies:
      - target: SnifLeaf-macOS
    scheme:
      testTargets:
        - SnifLeaf-macOSTests
      gatherCoverageData: true
  SnifLeaf-iOSTests:
    platform: macOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/SnifLeaf-iOSTests.xcconfig
    sources:
      - Tests/SnifLeaf-iOSTests
    dependencies:
      - target: SnifLeaf-iOS
    scheme:
      testTargets:
        - SnifLeaf-iOSTests
      gatherCoverageData: true
  SharedTests:
    platform: macOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/SharedTests.xcconfig
    sources:
      - Tests/SharedTests
    dependencies:
      - target: Shared
    scheme:
      testTargets:
        - SharedTests
      gatherCoverageData: true
  SnifLeafCoreTests:
    platform: macOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/SnifLeafCoreTests.xcconfig
    sources:
      - Tests/SnifLeafCoreTests
    dependencies:
      - target: SnifLeafCore
    scheme:
      testTargets:
        - SnifLeafCoreTests
      gatherCoverageData: true
